"""
End-to-end verification: waits for the real, unmodified Fluent Bit
`kinesis_streams` output plugin (shipping records generated by Fluent Bit's
own `dummy` input plugin) to publish through aws2azure into a Kinesis
Data Stream backed by Azure Event Hubs, then reads the records back via
plain boto3 `DescribeStream` / `GetShardIterator` / `GetRecords` calls
against the same aws2azure endpoint -- proving the full write path works
with a real, non-Python/non-JVM AWS SDK client (Fluent Bit is written in C).

Unlike the airflow-sns-fanout case study, this script talks to aws2azure on
*both* the write side (Fluent Bit) and the read side (this script) -- there
is no Kinesis-side "subscribe and forward" gap to work around, so the read
side does not need to bypass aws2azure.

Requires: `docker compose up -d` already run for the full stack (azurite,
eventhubs-emulator, aws2azure, fluent-bit), and aws2azure reachable at
http://localhost:8080 with a Host header starting with "kinesis." -- this
script relies on a /etc/hosts entry (added by the CI workflow / README)
mapping KINESIS_HOSTNAME to 127.0.0.1, since aws2azure routes services by
Host header and boto3 derives that header from its endpoint_url authority.
"""
import base64
import json
import sys
import time

import boto3
from botocore.config import Config

KINESIS_HOSTNAME = "kinesis.aws2azure.fluentbit-showcase.local"
ENDPOINT_URL = f"http://{KINESIS_HOSTNAME}:8080"
REGION = "us-east-1"
STREAM_NAME = "fluentbit-showcase-stream"
EXPECTED_SHARD_ID = "shardId-000000000000"
EXPECTED_SAMPLE_COUNT = 5
EXPECTED_MESSAGE = (
    "hello from the real Fluent Bit kinesis_streams output plugin, routed "
    "through aws2azure to Azure Event Hubs."
)
EXPECTED_SHOWCASE_ATTR = "fluentbit-kinesis"


def make_client():
    return boto3.client(
        "kinesis",
        region_name=REGION,
        endpoint_url=ENDPOINT_URL,
        aws_access_key_id="AKIA-FLUENTBIT-KINESIS-SHOWCASE",
        aws_secret_access_key="showcase-local-dev-secret-not-real",
        config=Config(retries={"max_attempts": 0}),
    )


def wait_for_proxy_ready(client, timeout=120):
    deadline = time.time() + timeout
    last_error = None
    while time.time() < deadline:
        try:
            describe = client.describe_stream(StreamName=STREAM_NAME)
            shards = describe["StreamDescription"]["Shards"]
            if len(shards) == 1 and shards[0]["ShardId"] == EXPECTED_SHARD_ID:
                print(f"aws2azure Kinesis endpoint is ready; stream has shard {shards[0]['ShardId']}")
                return
            last_error = f"unexpected shard topology: {shards!r}"
        except Exception as exc:  # noqa: BLE001 -- surfaced via sys.exit below
            last_error = exc
        time.sleep(3)
    sys.exit(f"aws2azure Kinesis endpoint did not become ready in time: {last_error}")


def read_all_records(client, timeout=90):
    iterator_response = client.get_shard_iterator(
        StreamName=STREAM_NAME,
        ShardId=EXPECTED_SHARD_ID,
        ShardIteratorType="TRIM_HORIZON",
    )
    shard_iterator = iterator_response["ShardIterator"]

    records = []
    deadline = time.time() + timeout
    while time.time() < deadline and len(records) < EXPECTED_SAMPLE_COUNT:
        response = client.get_records(ShardIterator=shard_iterator, Limit=100)
        records.extend(response["Records"])
        shard_iterator = response.get("NextShardIterator")
        if shard_iterator is None:
            break
        if not response["Records"]:
            time.sleep(2)
    return records


def main():
    client = make_client()
    wait_for_proxy_ready(client)

    records = read_all_records(client)
    if len(records) != EXPECTED_SAMPLE_COUNT:
        sys.exit(
            f"expected exactly {EXPECTED_SAMPLE_COUNT} records shipped by Fluent Bit's "
            f"dummy input (Samples={EXPECTED_SAMPLE_COUNT}), got {len(records)}"
        )

    for record in records:
        payload = record["Data"]
        if isinstance(payload, (bytes, bytearray)):
            payload = payload.decode("utf-8")
        else:
            # Some botocore versions hand back base64-encoded str for blob
            # shapes instead of already-decoded bytes; decode defensively.
            payload = base64.b64decode(payload).decode("utf-8")

        try:
            decoded = json.loads(payload)
        except json.JSONDecodeError as exc:
            sys.exit(f"record payload was not valid JSON: {payload!r} ({exc})")

        assert decoded.get("message") == EXPECTED_MESSAGE, (
            f"unexpected 'message' field in record: {decoded!r}"
        )
        assert decoded.get("showcase") == EXPECTED_SHOWCASE_ATTR, (
            f"unexpected 'showcase' field in record: {decoded!r}"
        )

    print(
        f"PASS: all {EXPECTED_SAMPLE_COUNT} records shipped by Fluent Bit's real, "
        "unmodified kinesis_streams output plugin were read back from aws2azure's "
        "Kinesis endpoint (backed by Azure Event Hubs) with their payloads intact"
    )


if __name__ == "__main__":
    main()
